[package]
name = "elef"
version = "0.1.0"
description = "Elef Markdown presentation renderer"
authors = ["Elef"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.7", features = ["dialog-open", "fs-read-file", "fs-write-file", "fs-create-dir", "fs-rename-file", "fs-read-dir", "fs-exists"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
